config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  default_url_options :host => "localhost:3000"
  root "pages#home"

  authenticate :user, lambda { |u| u.admin? } do
     mount Sidekiq::Web, at: '/sidekiq'
  end

  # Administrative control
  namespace :admin do
    resources :books, only: [:index, :edit, :update, :destroy]
  end

  resources :users, only: [:index, :show]

  resources :books do
    resources :offers, only: [:new, :create]
    resources :comments, only: [:new, :create, :edit, :destroy, :update]
    get 'search', on: :collection
    member do
       get 'buy'
     end
  end

  resources :offers, only: [:destroy, :edit] do
    member do
      get 'accept'
    end
  end

  resources :needs, only: [:new, :create, :destroy]

  resources :contact_forms, only: [:new, :create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books_owned, dependent: :destroy, class_name: 'Book'
  has_many :books_bought, dependent: :destroy, class_name: 'Book', foreign_key: :buyer_id
  has_many :books, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :needs, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  has_attached_file :avatar, styles: {
    medium: "300x300>",
    thumb: "100x100>",
    small: "50x50>", tiny: "25x25>"
  }, :default_url => ('/images/missing.png')

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  ## If we wanted to validate that all users had an avatar
  # validates :avatar, :attachment_presence => true
  validates :username, presence: true, uniqueness: true

  validates_formatting_of :firstname, :using => :alpha
  validates :firstname, presence: true,
    if: Proc.new { |user| user.sign_in_count > 0 }

  validates_formatting_of :lastname, :using => :alpha
  validates :lastname, presence: true,
    if: Proc.new { |user| user.sign_in_count > 0 }

  validates_formatting_of :phone, :using => :us_phone,
    if: Proc.new { |user| user.sign_in_count > 0 }

  validates :address, presence: { message: "University must be specified"},
    if: Proc.new { |user| user.sign_in_count > 0 }

  validates :year, presence: true,
    if: Proc.new { |user| user.sign_in_count > 0 }

  validates :phone, uniqueness: { allow_nil: true }

  validates :email, presence: true, format: { with: /(@dukes.jmu.edu)/,
    message: "%{value} is not a valid JMU email" }

  def self.years
    %w(Freshman Sophomore Junior Senior)
  end

  def self.university
    ['James Madison University']
  end

  def fullname
    "#{firstname.capitalize} #{lastname.first.capitalize}."
  end

  def admin?
    role == 'admin'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin, only: [:index]
  def index
    @users = User.all.order(username: :asc)
  end

  def show
    @user = current_user
    @recent_activities = Book.order(created_at: :desc).limit(3)
    sql = "SELECT count(offers.id) FROM offers JOIN books
          ON offers.book_id = books.id JOIN users ON users.id = books.user_id
          WHERE users.id = #{@user.id} AND books.sold = false;"

    @offer_count = ActiveRecord::Base.connection.execute(sql)
    @offer_count = @offer_count.first["count"]
  end

  private
    def authenticate_admin
      if !current_user.admin?
        flash[:notice] = "This page does not exist"
        redirect_to user_path(current_user)
      end
    end
end

app/views/users/index.html.erb
<h1>Users</h1>

<div class="row">
  <% @users.each do |u| %>
    <div class="col-md-3">
      <%=image_tag u.avatar.url(:medium), class: "modal-book" %>
      <h3><%= u.username %></h3>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<body class="dashboard-view">
  <div class="dashboard-pad">
    <div class="row">
      <div class="profile-tab col-md-4">
        <div class="row user-head">
          <div class="col-md-4 col-xs-5 center">
            <%= image_tag @user.avatar.url(:medium), class: "dash-pic" %>
          </div>
          <div class="col-md-8 col-xs-7 prof-info">
            <span class="dash-name"><%= @user.fullname %></span><br><p class='thin'><%= @user.address %><br><cite><%= link_to "Edit Profile", edit_user_registration_path %></cite></p>
          </div>
        </div>
        <div>
          <div class="row preview">
            <div class="col-xs-3 salmon center" type="button" data-toggle="tooltip" data-placement="bottom" title="Books added for sale">
              <%= @user.books.where(sold: "false").count %><br>Added
            </div>
            <div class="col-xs-3 seafoam center" type="button" data-toggle="tooltip" data-placement="bottom" title="Your pending bids">
              <%= @user.offers.where(accepted: "false").count %><br>Pending
            </div>
            <div class="col-xs-3 blue center" type="button" data-toggle="tooltip" data-placement="bottom" title="Books you've sold">
              <%= @user.books.where(sold: "true").count %><br>Sold
            </div>
            <div class="col-xs-3 purple center" type="button" data-toggle="tooltip" data-placement="bottom" title="Offers to accept">
              <%= @offer_count %><br>Offers
            </div>
          </div>
        </div>
        <div>
          <div class="recent-act center">
            <span class="dash-name">Recent Activity</span>
          </div>

          <% @recent_activities.each do |act| %>
            <div class="row">
              <div class="col-xs-2"><img src="<%= act.image_url %>" class="activity-img"></div>
              <div class="col-xs-8 user-info">
                <% if act.sold %>
                  <p><%= act.short_title %><br><span class="user-name thin"><%= act.user.fullname %></span></p>
                <% else %>
                  <p><%=link_to act.short_title, book_path(act) %><br>
                    <span class="user-name thin"><%= act.user.fullname %></span></p>
                <% end %>
              </div>
              <div class="col-xs-2">
                <% if act.sold == false %>
                  <span class=" buy-badge pull-right" type="button" data-toggle="tooltip" data-placement="bottom" title="Available"></span>
                <% else %>
                  <span class=" sold-badge pull-right" type="button" data-toggle="tooltip" data-placement="bottom" title="Sold"></span>
                <% end %>
              </div>
            </div>
            <div class='line-break'></div>
          <% end %>

        </div>
      </div>

      <div class="col-md-8 no-col-pad no-rt-pad">
        <div class="wishlist-tab profile-tab">
        <div class="row">
          <div class="col-xs-1 hidden-xs">
            <%= image_tag('menu.png', class: "menu-img", id: "menu-icon") %>
          </div>
          <div class="col-xs-4 no-right-pad">
            <h2 class="thin">Wishlist</h2>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-5 pull-right explore">
            <button class="bh-btn" id="details">Explore <span class="caret"></span></button>
          </div>
        </div>

        <% if @user.needs.length == 0 %>
        <div id="wishlist">
        <% else %>
        <div id="wishlist" hidden>
        <% end %>
          <% if current_user.needs == [] %>
            <p class="thin med-fnt grey-fnt">Add a book now! You will be notified as soon as another user adds that book.</p>
          <% else %>
            <p class="thin med-fnt grey-fnt">Click for details...</p>
            <div class="row">
              <% current_user.needs.each do |need| %>
              <div class="wish-item col-sm-1 col-xs-2">
                <div data-toggle="modal" data-target="#showModal<%= need.id %>">
                  <a href="<%= need.amazon_url %>" target="_blank"><img src="<%= need.image_url %>" class="wish-book"></a>
                  <br>
                </div>
              </div>
              <% end %>
            </div>
          <% end %>
          <%= link_to "Add Book to Wishlist", new_need_path %>
        </div>
        </div>
      </div>

      <div class="col-md-8 no-col-pad no-rt-pad center">
        <div class=" main-tab ">
        <div class="tab-header xs-border salmon"><h3>My Books For Sale</h3></div>
        <p class="data-stat"><%= "You have #{@user.books.where(sold: "false").count} book(s) in your library" %></p>
          <% @user.books.order(title: :asc).each do |book| %>
          <% if book.sold == false %>
          <div class="book-details"><%= book.title %><span class="caret"></span>
            <div hidden>
              <%= link_to 'Details', book_path(book) %> |
              <%= link_to "Edit", edit_book_path(book.id) %> | <%= link_to "Delete", book, method: :delete, data: {confirm: "Are you sure you want to delete this book from your library?"}, class: "red" %>
            </div>
          </div>
          <% end %>
          <% end %>
        <%= link_to "Add Book", new_book_path, class: "add-book-link" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4 tab-padding center">
        <div class="mini-tab">
          <div class="tab-header xs-border seafoam"><h3>My Bids</h3></div>
          <p class="data-stat"><%= "You have #{@user.offers.where(accepted: "false").count} pending bid(s)" %></p>
          <% @user.offers.each do |offer| %>
            <div class="btn btn-sm btn-default book-details">
              <% if offer.book.sold == true %>
                <span class="red"><%= offer.book.title %> | Sold <span class="caret"></span></span>
              <% else %>
                <%= offer.book.title %> <span class="caret"></span>
              <% end %>
              <div hidden>
                You offered: $<%= offer.amount %><br>
                Seller: <%= offer.book.user.fullname %><br>
                <% if offer.book.sold == true %>
                  <%= link_to "Delete", offer, method: :delete, class: "red", data: {confirm: "Are you sure you want to remove this offer?"} %><br>
                <% else %>
                <%= link_to "Revoke", offer, method: :delete, class: "red", data: {confirm: "Are you sure you want to remove this offer?"} %><br>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="col-sm-4 tab-pad-left center">
        <div class="mini-tab">
          <div class="tab-header xs-border blue"><h3>Books Sold</h3></div>
          <p class="data-stat"><%= "You have sold #{@user.books.where(sold: "true").count} book(s)" %></p>
            <% @user.books.each do |book| %>
              <% if book.sold == true %>
                <div class="details">
                  <div class="btn btn-sm btn-default book-details">
                    <%= book.short_title %> <span class="caret"></span>
                    <div class='buyer-info' hidden>
                      <%= book.buyer.email %><br> <%= book.buyer.phone %> | Offer: $<%= book.price %>.00
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
        </div>
      </div>

      <div class="col-sm-4 tab-padding center">
        <div class="mini-tab">
          <div class="tab-header xs-border purple"><h3>My Offers</h3></div>
          <p class="data-stat"><%= "You have #{@offer_count} offer(s) from other peers" %></p>
            <% @user.books.each do |book| %>
              <% book.offers.order(created_at: :desc).each do |offer| %>
                <% if book.sold == false %>
                    <div class='btn btn-sm btn-default book-details btn-space'>
                      <%= book.title %> <span class='caret'></span>
                      <div hidden>
                        Offer: $<%= offer.amount %> | Bidder: <%= offer.user.fullname %><br>
                        <%= link_to "Accept",{controller: :offers, action: :accept, id: offer.id} , class: "green" %>
                      </div>
                    </div>
                <% end %>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
  </div>


  <!-- Modal -->
  <% current_user.needs.each do |need| %>
  <div class="modal fade" id="showModal<%= need.id %>" tabindex="-1" role="dialog" aria-labelledby="showModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel"><%= need.title %></h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class='col-md-4 center'>
              <img src="<%= need.image_url %>" class="modal-book">
            </div>
            <div class='col-md-8'>
              <div><h1 class="modal-book-title thin"><%= need.title %><h1></div>
              <div><h3 class="modal-author thin"><%= need.author %></div></h3><br>
              <a href="<%= need.amazon_url %>" target='_blank'>Buy on Amazon</a>
              <div><%= link_to "Delete", need, method: :delete, data: {confirm: "Are you sure you want to delete this book from your wishlist?"}, class: "red"%>
              </div>
            </div>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<%= content_for :extra_footer do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('#menu-icon').click(function(){
        $('#wishlist').toggle("medium");
      });

      $('.book-details').click(function(){
        $(this).children('div').toggle('medium');
      })

      var updateWishlistButton = function() {
        if ($('#wishlist').is(':visible')) {
          $('#details').html('Hide');
        } else {
          $('#details').html('Explore');
        }
      };

      updateWishlistButton();

      $('#details').click(function(){
        $('#wishlist').toggle("medium");
        updateWishlistButton();
      });

      $(function () { $("[data-toggle='tooltip']").tooltip(); });
    });
  </script>
<% end %>

</body>