config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  default_url_options :host => "localhost:3000"
  root "pages#home"

  authenticate :user, lambda { |u| u.admin? } do
     mount Sidekiq::Web, at: '/sidekiq'
  end

  # Administrative control
  namespace :admin do
    resources :books, only: [:index, :edit, :update, :destroy]
  end

  resources :users, only: [:index, :show]

  resources :books do
    resources :offers, only: [:new, :create]
    resources :comments, only: [:new, :create, :edit, :destroy, :update]
    get 'search', on: :collection
    member do
       get 'buy'
     end
  end

  resources :offers, only: [:destroy, :edit] do
    member do
      get 'accept'
    end
  end

  resources :needs, only: [:new, :create, :destroy]

  resources :contact_forms, only: [:new, :create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :buyer, class_name: "User"
  has_many :offers, dependent: :destroy

  validates :title, presence: true,
    if: Proc.new { |book| book.isbn13.blank? }
  validates :quality, presence: true
  validates_formatting_of :course_title, using: :alphanum, allow_blank: true
  validates :price, numericality: { only_integer: true }, length: { maximum: 3 }
  validates :isbn,
    isbn_format: { with: :isbn },
    uniqueness: { scope: :user_id, message: "You have already added this book" },
    allow_blank: true

  validates :isbn13,
    isbn_format: { with: :isbn13 },
    presence: true,
    if: Proc.new { |book| book.title.blank? },
    uniqueness: { scope: :user_id, message: "You have already added this book" }

  before_validation :format_title, :find_book_in_db,
    unless: :admin?

  def admin?
    user.admin?
  end

  def self.qualities
    %w(New Good Decent )
  end

  def self.count(user_id)
    user_books = Book.all.where(sold: :false, user_id: user_id).count
    library = Book.all.where(sold: :false).count
    library - user_books
  end

  def course_title
    super.split.map! {|word| word.upcase }.join(' ') unless super.blank?
  end

  def price
    super.to_f.round(0)
  end

  def set_author(arg)
    if arg.nil?
      self.author = nil
    elsif arg[0..2] == "by "
      author = arg[3..-1]
      if arg[-2..-1] == ", "
        author = arg[0..-3]
      end
      self.author = arg
    else
      self.author = arg[0..-3]
    end
  end


  def short_title
    if self.title.length > 20
      "#{title[0..20]}.."
    else
      title
    end
  end

  protected

  def format_title
    lowercase = %w(a an the for and nor but or yet so at by after along from of on to with is)
    title = self.title.split
    arr = []
    title.each do |word|
      if lowercase.include?(word)
        arr << word.downcase
      else
        arr << word.capitalize
      end
    end
    if arr != []
      arr.first.capitalize!
      arr.last.capitalize!
      title = arr.join(' ')
      self.title = title
    end
  end

  def convert_to_isbn13
    if self.isbn.present?
      isbn = "978" + self.isbn
      isbn_10 = isbn[0..11].split('')
      isbn_13 = nil

      sum = 0
      counter = 0
      isbn_10.each do |n|
        if counter%2 == 1
            sum += n.to_i * 3
            counter += 1
        else
          sum += n.to_i
          counter += 1
        end
      end

      remainder = sum%10

      if remainder == 0
        check_digit = 0
      else
        check_digit = 10 - remainder
      end

      self.isbn13 = isbn_10.join('') + check_digit.to_s
    end
  end

  def find_book_in_db
    client = ASIN::Client.instance

    # If user doesn't add by title they can add by isbn13
    if self.title.length == 0
      query = client.search_keywords(self.isbn13).first
    else
      query = client.search_keywords(self.title).first
    end
    # Test to make sure we get a result form Amazon
    if query != nil
      attributes = query.item_attributes
      self.title = attributes.title unless self.title.present?
      # Test for ISBN-10 or ISBN-13
      if attributes.isbn.length == 10
        self.isbn = attributes.isbn
        if self.isbn13.blank?
          convert_to_isbn13
        end
      else
        if self.isbn13.blank?
          self.isbn13 = attributes.isbn
        end
      end

      # Test for whether there are multiple authors
      if attributes.author.kind_of?(Array)
        authors = ""
        attributes.author.each_with_index { |author, index|
          if index == 0
            authors << author
          else
          authors << ", #{author}"
          end
        }
        self.author = authors
      else
        self.author = attributes.author unless self.author.present?
      end

      self.image_url = query.large_image.url
      self.amazon_url = query.detail_page_url
      self.used_price = format_suggested_price(query.offer_summary.lowest_used_price.amount)
      self.new_price = format_suggested_price(query.offer_summary.lowest_new_price.amount)
    end
  end

  def format_suggested_price(price)
    (price.to_f / 100).round
  end

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :check_admin

  def index
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "#{@book.title} has been successfully updated"
      redirect_to admin_books_path
    else
      flash[:notice] = "There were errors in your submission"
      render :admin_edit
    end
  end

  def destroy
    @book = Book.find(params[:id]).destroy

    flash[:notice] = "#{@book.title} has been deleted."
    redirect_to admin_books_path
  end

  protected
  def check_admin
    if !current_user.admin?
      flash[:notice] = "This page does not exist"
      redirect_to root_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :isbn13, :author, :image_url, :amazon_url)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :destroy]
  def index
    @books = Book.all.order(created_at: :desc)

    ##Location-based books
    # users = User.all.near(current_user, 15)
    # @books = []
    # users.each do |user|
    #   user.books.each do |book|
    #     @books << book
    #   end
    # end
  end

  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
    @offer = Offer.new
  end

  def new
    @book = current_user.books.build
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      if @book.amazon_url.present?
        UpdateSearch.perform_async(@book.id)
        redirect_to edit_book_path(@book), notice: "Make sure this information is correct!"
      else
        @book.destroy
        redirect_to new_book_path
        flash[:notice] = 'Book could not be found. Please try the ISBN'
      end
    else
      render action: 'new'
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      flash[:notice] = "Something went wrong!"
      render :edit
    end
  end

  def search
    query = "%#{params[:query]}%"
    query.downcase
    @books = Book.where('title ilike ? or course_title ilike ? or isbn ilike ? or isbn13 ilike ? or author ilike ?',
             query, query, query, query, query)
  end

  def buy
    @book = Book.find(params[:id])
    @book.buyer = current_user
    @book.sold = true
    @book.save
    UserMailer.purchase_email(current_user, @book.user, @book).deliver

    flash[:notice] = "#{@book.title} has been marked as purchased. The Seller has been notified"
    redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:id]).destroy

    flash[:notice] = "#{@book.title} has been deleted from your library"
    redirect_to user_path(current_user)
  end

protected
  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    if @book.nil?
      flash[:notice] = "This page does not exist"
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :quality, :course_title, :price, :isbn, :isbn13, :author, :image_url, :used_price, :new_price, :amazon_url)
  end
end

app/views/books/_form.html.erb
<div class="center">
  <% if @book.errors.any? %>
    <p> There were errors in your submission </p>
    <ul>
      <% @book.errors.each do |key, val| %>
        <li><%= key.capitalize %> <%= val %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for [@user, @book] do |f| %>
    <div class="col-xs-12">
      <%= f.text_field :title, autofocus: true, placeholder: "Book Title", class: "book-info" %><br><br>
    </div>

    <div class="col-xs-12">
      <%= f.text_field :isbn13, autocomplete: "off", placeholder: "ISBN-13", class: "book-info" %><br><br>
    </div>

    <div class="col-xs-12">
      <%= f.select :quality, Book.qualities, prompt: "Select Book Quality", class: "quality-input" %>
    </div><br>

    <div class="row">
      <div class="book_price_input ">
        <div><%= f.label :price %></div>
        <div class="col-sm-2 col-sm-offset-4">
        <span class="price-hlpr">$</span> <%= f.text_field :price,autocomplete: "off", placeholder: "20", class: "amount-input" %><span class="price-hlpr">.00</span>
        </div>
      </div>

      <div class="col-sm-2 col-xs-12">
        <span class="price-hlpr">Open for Bids</span> <input type="checkbox" class="price_toggle">
      </div>
    </div>

    <div class="col-xs-12"><%= f.submit "Submit", class: "book-info submit-btn"%></div><br><br>
  <% end %>

  <%= link_to 'Back', :back %>
</div>

<%= content_for :extra_footer do %>
  <script type="text/javascript">
    $(document).ready(function(){
      var $bookTitle = $('#book_title');
      var $bookISBN = $('#book_isbn13');
      var $priceToggle = $('.price_toggle');

      $bookTitle.keyup(function() {
        if ($(this).val().length > 0) {
          $bookISBN.parent().hide('medium');
        } else {
          $bookISBN.parent().show('medium');
        }
      });

      $bookISBN.keyup(function() {
        if ($(this).val().length > 0) {
          $bookTitle.parent().hide('medium');
        } else {
          $bookTitle.parent().show('medium');
        }
      });

      $priceToggle.click(function(){
        if ($('.book_price_input').is(':visible')) {
          $('.book_price_input').hide();
          $(this).parent().attr('class', 'col-xs-12');
        } else {
          $('.book_price_input').show();
          $(this).parent().attr('class', 'col-sm-2 col-xs-12');
        }
      });
    });
  </script>
<% end %>

app/views/books/edit.html.erb
<div class="center">
<h1 class="page-title">Edit Book</h1>

<% if @book.errors.any? %>
  <p> There were errors in your submission </p>
  <ul>
    <% @book.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
  </ul>
<% end %>

<div id="edit-book-form">
  <%= form_for [@user, @book] do |f| %>
    <div class="row">
      <div class="col-sm-1 col-sm-offset-4 col-xs-12">
        <img src="<%= @book.image_url %>" class="book-image">
      </div>

      <div class="col-sm-4 col-xs-12">
          <div><%= f.label "Author", class: "thin med-fnt" %></div>
          <%= f.text_field :author, autofocus: true, placeholder: "Alex Morgan", class: "author-info" %>
          <div><%= f.label :course_title, "Course Title", class: "thin med-fnt" %></div>
          <%= f.text_field :course_title, placeholder: "GCOM 101", class: "author-info" %>
      </div>
    </div>

    <div class="row">
    <div class="col-xs-12">
      <div><%= f.label :title, "Book Title", class: "thin med-fnt" %></div>
      <%= f.text_field :title, placeholder: "ex: Book (9th Edition)", class: "book-info" %>
    </div>

    <div class="col-xs-12">
      <div><%= f.label :quality, class: "thin med-fnt" %></div>
      <%= f.select :quality, Book.qualities, prompt: "Select book quality", class: "book-info" %>
    </div>

    <div class="col-xs-12">
      <div><%= f.label :price, class: "thin med-fnt" %></div>
      $ <%= f.text_field :price, placeholder: "20", class: "amount-input" %>.00
    </div>

    <div class"col-xs-12"><%= f.submit "Confirm", class: "btn btn-success"%></div>
    </div>
  <% end %>
</div>

<div class="col-sm-6 col-sm-offset-3">
  <div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
    </div>
  </div>
</div>


<!-- <div>
  <% if @book.used_price > 0 %>
    <i>Used Price: </i>$<%= @book.used_price %>.00
  <% end %>
</div>
<div>
  <% if @book.new_price > 0  %>
    <i>New Price: </i>$<%= @book.new_price %>.00
  <% end %>
</div> -->

</div>

<%= content_for :extra_footer do %>
  <script type="text/javascript">
    $(document).ready(function(){

      var updateProgressBar = function() {
        var fields = 6,
        filled = fields;

        $('#edit-book-form :input').each(function() {
          if ($(this).val() == '') {
            filled --;
          };
        });

        var percentComplete = (filled / fields)*100;
        $('.progress-bar').attr('style', "width:" + percentComplete + '%');
      };

      updateProgressBar();

      $(":input").keyup(updateProgressBar);
    });
  </script>
<% end %>

app/views/books/index.html.erb
<h1 class="page-title">Books:</h1>
<p><%= Book.count(current_user) %> Book(s) in Library</p>

<%= form_tag(search_books_path, method: :get) do %>
<%= text_field_tag 'query', nil, class: 'span4 search-query', placeholder: "Search by book, course, author, or isbn", class: "search" %>
<% end %>
<div class="row">
</div>
  <% @books.each do |book| %>
    <% if book.sold == false %>
      <% if current_user != book.user %>
        <div class="col-sm-3 col-xs-6 center">
          <a href="<%= book_path(book) %>">
            <% if book.image_url != nil %>
              <img src="<%= book.image_url %>" class="book-index">
            <% end %><br>
          </a>
          <div class="col-md-12">
            <%= link_to "#{book.short_title}", book_path(book) %>
          </div>
          <div class="col-xs-12">
            <p>
              <% if book.price == 0 %>
                Make Offer
              <% else %>
                $<%= book.price %>
              <% end %>
              | <%= book.quality %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>

app/views/books/new.html.erb
<div class="col-md-12 center">
  <h1 class="page-title">Add Book</h1>
</div>

<%= render "form" %>

app/views/books/search.html.erb
<h1 class="page-title">Search Results</h1>

<br />

<% if @books.empty? %>

<p>No results found.</p>

<% else %>

<p><%= "#{@books.where(sold: "false").count} result(s) found." %></p>

<ul class="unstyled">
  <% @books.each do |book| %>
    <% if book.sold == false %>
      <li>
        <%= link_to book.title, book %>
      </li>
    <% end %>
  <% end %>
</ul>
<% end %>

<%= link_to 'Back', :back %>

app/views/books/show.html.erb
<div class= "col-md-6">
  <h1 class="book-title"><%= @book.title %></h1>
  <% if @book.image_url != nil %>
    <img src="<%= @book.image_url %>" class="book-image">
  <% end %>
  <% if @book.author != "" && @book.author != nil %>
    <h5>by <%= @book.author %></h5>
  <% end %>
  <% if @book.isbn.present? %>
    <p><b>ISBN: </b><i><%= @book.isbn %></i><p>
  <% end %>
    <p><b>ISBN 13: </b><i><%= @book.isbn13 %></i></p>

  <% if @book.course_title.present? %>
    <h3>Course</h3>
    <h5><%= @book.course_title %></h5>
  <% end %>

  <h3>Quality</h3>
  <h5><%= @book.quality %></h5>

  <h3>Seller</h3>
  <% if @book.user_id != current_user.id %>
    <p><%= image_tag @book.user.avatar.url(:tiny), class: "tiny-avatar" %> <%= @book.user.fullname %></p>
  <% else %>
    <h5>You</h5>
  <% end %>
</div>

<% if @offer.errors.any? %>
  <p> There were errors in your submission </p>
  <ul>
    <% @offer.errors.each do |key, val| %>
      <li><%= val %></li>
    <% end %>
  </ul>
<% end %>

    <div class="well col-md-3">
      <div class="center">
        <% if current_user == @book.user %>
          <h3>Your offer</h3>
        <% else %>
          <h3>Make an Offer</h3>
        <% end %>
      </div>
      <% if @book.price == 0 %>
        <% if current_user != @book.user %>
          <%= form_for [@book, @offer] do |f| %>
            <div>
              <%= f.label :amount %><br>
              $ <%= f.text_field :amount, placeholder: "20", class: "amount-input" %>.00
            </div><br>
            <div><%= f.submit "Make Offer", class: "btn btn-success" %></div>
          <% end %>
        <% else %>
          <div class="center"><p>Open For Offers</p></div>
        <% end %>
      <% else %>
        <p>Price</p>
        <div>$<%= @book.price %>.00</div><br>
        <div>
          <% if @book.user != current_user && @book.sold == false %>
            <%= link_to "Buy!",{controller: :books, action: :buy, id: @book.id} , class: "btn btn-success" %>
          <% end %>
        </div>
      <% end %>
    </div>

<% if false %>
<!-- <div class="col-md-10">
<h3>Leave Comment</h3>
<%= form_for [@book, @comment] do |f| %>
  <div>
    <%= f.text_area :body, placeholder: "Leave a comment for #{@book.user.fullname}" %>
  </div><br>
  <%= f.submit "Leave Comment" %>
<% end %>
</div> -->
<% end %>

<div class="row col-md-10">
  <div class="col-md-1">
    <%= link_to "Back", :back, class: "btn btn-primary" %>
  </div>
  <div class="col-md-1">
    <% if @book.sold == true %>
      <button class="btn btn-danger" disabled>sold</button>
    <% end %>
  </div>
</div>