config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  default_url_options :host => "localhost:3000"
  root "pages#home"

  authenticate :user, lambda { |u| u.admin? } do
     mount Sidekiq::Web, at: '/sidekiq'
  end

  # Administrative control
  namespace :admin do
    resources :books, only: [:index, :edit, :update, :destroy]
  end

  resources :users, only: [:index, :show]

  resources :books do
    resources :offers, only: [:new, :create]
    resources :comments, only: [:new, :create, :edit, :destroy, :update]
    get 'search', on: :collection
    member do
       get 'buy'
     end
  end

  resources :offers, only: [:destroy, :edit] do
    member do
      get 'accept'
    end
  end

  resources :needs, only: [:new, :create, :destroy]

  resources :contact_forms, only: [:new, :create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoBrainr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>
  <%= yield :extra_head %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">NoBrainr</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li id="users"><a href="<%= books_path %>">Books</a></li>
          <li id="add-book"><a href="<%= new_book_path %>">Add Book</a></li>
          <% if current_user.try(:admin?) %>
            <li><a href="<%= sidekiq_web_path %>">Sidekiq</a></li>
            <li><a href="<%= admin_books_path %>">Admin</a></li>
          <% end %>
        </ul>
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          <%= image_tag current_user.avatar.url(:tiny), class: "tiny-avatar" %>
          <strong><%= link_to current_user.username, user_path(current_user.id), :class => 'navbar-link' %> |</strong>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="site-content">
    <%= yield :map %>
  </div>

  <% flash.each do |name, msg| %>
    <div class="flash center">
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    </div>
  <% end %>

  <div class="container">
    <div class="site-content">
      <%= yield %>
    </div>
  </div>

  <%= yield :footer %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>